train_data_path: data/data/images
test_data_path: data/data_refined/CatBreedsRefined-v2
labels2id_meta: data/labels_metainfo/labels2id_metainfo.json
id2labels_meta: data/labels_metainfo/id2labels_metainfo.json
